//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mi_first_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Book
    {
        [Display(Name = "#")]
        public int Id { get; set; }
        [Display(Name = "Name Book")]

        public string NameBook { get; set; }
        [Display(Name = "Name of Author")]

        public string Author { get; set; }

        [Display(Name = "Date")]
        [DisplayFormat(ApplyFormatInEditMode =true, DataFormatString ="{0:MM/dd/yyy}")]
        [DataType(DataType.DateTime)]


        public System.DateTime DateTime { get; set; }
    }
}
